# Generated by Django 2.2.1 on 2020-10-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=25)),
                ('last', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=55)),
                ('number', models.CharField(blank=True, max_length=25)),
                ('date', models.DateField(blank=True, max_length=25)),
                ('time', models.TimeField(blank=True, max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='carshop',
            name='date',
        ),
        migrations.RemoveField(
            model_name='carshop',
            name='number',
        ),
        migrations.RemoveField(
            model_name='carshop',
            name='time',
        ),
    ]
