# Generated by Django 2.2.1 on 2020-10-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201020_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shash',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shash',
            name='time',
        ),
        migrations.AddField(
            model_name='shash',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shash',
            name='number',
            field=models.IntegerField(blank=True, max_length=25),
        ),
    ]
