# Generated by Django 2.2.1 on 2020-10-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201020_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shash',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='shash',
            name='nm',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='shash',
            name='sh',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='shash',
            name='number',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
