# Generated by Django 2.2.1 on 2020-10-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201020_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shash',
            name='nm',
        ),
        migrations.RemoveField(
            model_name='shash',
            name='number',
        ),
        migrations.RemoveField(
            model_name='shash',
            name='sh',
        ),
        migrations.AddField(
            model_name='shash',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
