# Generated by Django 2.2.1 on 2020-10-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201020_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='shash',
            name='number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
