# Generated by Django 2.2.1 on 2020-10-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_shash_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shash',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='shash',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
